import JSZip from "jszip";

export const runtime = "nodejs";

type Tradeoffs = {
  speedVsQuality: number;     // -2..2
  simplicityVsPower: number;  // -2..2
  safetyVsFreedom: number;    // -2..2
};

type Payload = {
  productName: string;
  oneLiner: string;
  palettes: string[];
  tradeoffs: Tradeoffs;
};

function clampInt(n: unknown, min: number, max: number, fallback: number): number {
  const x = typeof n === "number" ? n : Number(n);
  if (!Number.isFinite(x)) return fallback;
  const xi = Math.round(x);
  return Math.max(min, Math.min(max, xi));
}

function asString(x: unknown, fallback = ""): string {
  return typeof x === "string" ? x : fallback;
}

function asStringArray(x: unknown): string[] {
  if (!Array.isArray(x)) return [];
  return x.filter((v) => typeof v === "string") as string[];
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ ok: false, error: "Invalid JSON body." }, null, 2), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const p = body as Partial<Payload>;

  const productName = asString(p.productName).trim();
  const oneLiner = asString(p.oneLiner).trim();
  const palettes = asStringArray(p.palettes);

  if (!productName) {
    return new Response(JSON.stringify({ ok: false, error: "productName is required." }, null, 2), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const tradeoffs: Tradeoffs = {
    speedVsQuality: clampInt(p.tradeoffs?.speedVsQuality, -2, 2, 0),
    simplicityVsPower: clampInt(p.tradeoffs?.simplicityVsPower, -2, 2, 0),
    safetyVsFreedom: clampInt(p.tradeoffs?.safetyVsFreedom, -2, 2, 0),
  };

  const createdAt = new Date().toISOString();

  const intake = {
    schema: "sdde.intake.v1",
    created_at_utc: createdAt,
    product: {
      name: productName,
      one_liner: oneLiner || "",
    },
    launch_path: "quick_saas_v1",
    surfaces: ["web"],
    ai: {
      mode: "offline",
      note: "Offline builder-first. Enable hosted/local later via env + contracts.",
    },
  };

  const palettesDoc = {
    schema: "sdde.palettes.selected.v1",
    selected: palettes,
  };

  const tradeoffsDoc = {
    schema: "sdde.tradeoffs.v1",
    scale: { min: -2, max: 2, meaning: "-2 = left, 0 = neutral, +2 = right" },
    axes: {
      speed_vs_quality: tradeoffs.speedVsQuality,
      simplicity_vs_power: tradeoffs.simplicityVsPower,
      safety_vs_freedom: tradeoffs.safetyVsFreedom,
    },
  };

  const readme = `# SDDE Spec Pack (Offline)

This zip was generated by the Kindred v2 Builder in Offline mode.

## Files
- intake.json — basic intent & launch path
- palettes.json — selected Interaction Palettes
- tradeoffs.json — initial tradeoff posture
- manifest.json — metadata about this pack

## Next step (manual for now)
Open SDDE Workbench / SDDE tools and import this pack to create a governed project workspace.

This is intentionally offline-first:
- No wallet required
- No API keys required
- No database required
`;

  const manifest = {
    schema: "sdde.spec_pack.manifest.v1",
    created_at_utc: createdAt,
    generator: "kindred-official-v2 (offline builder)",
    contents: ["intake.json", "palettes.json", "tradeoffs.json", "README.md", "manifest.json"],
  };

  const zip = new JSZip();
  zip.file("intake.json", JSON.stringify(intake, null, 2));
  zip.file("palettes.json", JSON.stringify(palettesDoc, null, 2));
  zip.file("tradeoffs.json", JSON.stringify(tradeoffsDoc, null, 2));
  zip.file("README.md", readme);
  zip.file("manifest.json", JSON.stringify(manifest, null, 2));

  const bytes = await zip.generateAsync({ type: "arraybuffer" });
  const blob = new Blob([bytes], { type: "application/zip" });

  return new Response(blob, {
    status: 200,
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": 'attachment; filename="sdde_spec_pack.zip"',
      "Cache-Control": "no-store",
    },
  });
}
