"use client";

import { encodeBase64 } from "./spec_pack";
import { sha256Hex } from "./hash";
import { stableJsonText } from "./stable_json";
import { APP_VERSION, VALIDATOR_VERSION, ZIP_MTIME_UTC } from "./version";
import type { RepoPack } from "./repo_pack_io";
import type { RepoPackPatchV1, RepoPatchOpV1 } from "./repo_pack_patch";
import { REPO_PACK_PATCH_SCHEMA_ID } from "./repo_pack_patch";
import { computeRepoPatchOpsHash } from "./repo_pack_governance";

export const DOGFOOD_REPORT_SCHEMA_ID = "kindred.dogfood_report.v1" as const;

export type DogfoodReportV1 = {
  schema: typeof DOGFOOD_REPORT_SCHEMA_ID;
  ran_at_utc: string;
  project_id: string;
  base: {
    repo_id?: string;
    pack_sha256: string;
    file_count?: number;
    total_bytes?: number;
  };
  patch: {
    ops_sha256: string;
    operation: "add" | "edit";
    path: string;
  };
  locked: {
    repo_id?: string;
    pack_sha256: string;
    zip_sha256: string;
    file_count?: number;
    total_bytes?: number;
  };
  exported?: {
    locked_zip_sha256: string;
  };
  provenance?: {
    app_version?: string;
    validator_version?: string;
  };
  notes?: string[];
};

const DOGFOOD_REPORT_KEY_PREFIX = "kindred_dogfood_report_v1:";

function utcNow(): string {
  return new Date().toISOString();
}

function dispatch(name: string) {
  try {
    window.dispatchEvent(new CustomEvent(name));
  } catch {
    // ignore
  }
}

export function dogfoodReportKeyForProject(projectId: string): string {
  return `${DOGFOOD_REPORT_KEY_PREFIX}${projectId}`;
}

export function getDogfoodReport(projectId: string): DogfoodReportV1 | null {
  try {
    const raw = localStorage.getItem(dogfoodReportKeyForProject(projectId));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as any;
    if (!parsed || parsed.schema !== DOGFOOD_REPORT_SCHEMA_ID) return null;
    return parsed as DogfoodReportV1;
  } catch {
    return null;
  }
}

export function setDogfoodReport(projectId: string, report: DogfoodReportV1): void {
  try {
    // Stable formatting makes the downloaded report diff-friendly.
    localStorage.setItem(dogfoodReportKeyForProject(projectId), stableJsonText(report, 2));
  } catch {
    // ignore
  }
  dispatch("kindred_dogfood_report_changed");
}

export async function createDogfoodPatchForBasePack(basePack: RepoPack): Promise<{
  patch: RepoPackPatchV1;
  operation: "add" | "edit";
  path: string;
}> {
  const targetPath = "docs/DOGFOOD_PROOF.md";
  const existing = basePack.fileMap.get(targetPath);

  const basePackSha = basePack.pack_sha256;
  const repoId = basePack.manifest.repo_id || "";

  const contentLines: string[] = [];
  contentLines.push("# Kindred Dogfood Proof");
  contentLines.push("");
  contentLines.push("This file is generated by Kindred AI Builders Dogfood mode.");
  contentLines.push("It is deterministic for a given Base Repo Pack (no wall-clock time encoded).");
  contentLines.push("");
  if (repoId) contentLines.push(`Base repo_id: ${repoId}`);
  contentLines.push(`Base pack_sha256: ${basePackSha}`);
  contentLines.push(`Generated by app_version: ${APP_VERSION}`);
  contentLines.push("");
  contentLines.push("To reproduce:");
  contentLines.push("- Import the same Base repo ZIP into /repo");
  contentLines.push("- Run Dogfood mode again");
  contentLines.push("");
  const content = contentLines.join("\n") + "\n";

  const bytes = new TextEncoder().encode(content);
  const newSha = await sha256Hex(bytes);

  const fileCount = typeof basePack.manifest.totals?.file_count === "number" ? basePack.manifest.totals.file_count : basePack.files.length;
  const unchanged = Math.max(0, fileCount - (existing ? 1 : 0));

  const ops: RepoPatchOpV1[] = [];
  let operation: "add" | "edit" = "add";

  if (!existing) {
    ops.push({
      op: "add",
      path: targetPath,
      new_b64: encodeBase64(bytes),
      new_sha256: newSha,
      new_size: bytes.byteLength,
      is_text: true,
    });
    operation = "add";
  } else {
    ops.push({
      op: "edit",
      path: targetPath,
      old_sha256: existing.sha256,
      old_size: existing.size,
      new_b64: encodeBase64(bytes),
      new_sha256: newSha,
      new_size: bytes.byteLength,
      is_text: true,
    });
    operation = "edit";
  }

  const patch: RepoPackPatchV1 = {
    schema: REPO_PACK_PATCH_SCHEMA_ID,
    created_at_utc: ZIP_MTIME_UTC,
    summary: `Dogfood: ${operation} ${targetPath}`,
    patch_text: `DOGFOOD: ${operation.toUpperCase()} ${targetPath}`,
    stats: {
      added: operation === "add" ? 1 : 0,
      deleted: 0,
      edited: operation === "edit" ? 1 : 0,
      moved: 0,
      unchanged,
    },
    ops,
    provenance: {
      app_version: APP_VERSION,
      validator_version: VALIDATOR_VERSION,
    },
  };

  return { patch, operation, path: targetPath };
}

export async function createDogfoodReport(opts: {
  projectId: string;
  basePack: RepoPack;
  operation: "add" | "edit";
  path: string;
  patch: RepoPackPatchV1;
  lockedZipBytes: Uint8Array;
  lockedPackSha256: string;
  lockedRepoId?: string;
  lockedFileCount?: number;
  lockedTotalBytes?: number;
}): Promise<DogfoodReportV1> {
  const opsSha = await computeRepoPatchOpsHash(opts.patch);
  const lockedZipSha = await sha256Hex(opts.lockedZipBytes);

  return {
    schema: DOGFOOD_REPORT_SCHEMA_ID,
    ran_at_utc: utcNow(),
    project_id: opts.projectId,
    base: {
      repo_id: opts.basePack.manifest.repo_id,
      pack_sha256: opts.basePack.pack_sha256,
      file_count: opts.basePack.manifest.totals?.file_count,
      total_bytes: opts.basePack.manifest.totals?.total_bytes,
    },
    patch: {
      ops_sha256: opsSha,
      operation: opts.operation,
      path: opts.path,
    },
    locked: {
      repo_id: opts.lockedRepoId,
      pack_sha256: opts.lockedPackSha256,
      zip_sha256: lockedZipSha,
      file_count: opts.lockedFileCount,
      total_bytes: opts.lockedTotalBytes,
    },
    exported: {
      locked_zip_sha256: lockedZipSha,
    },
    provenance: {
      app_version: APP_VERSION,
      validator_version: VALIDATOR_VERSION,
    },
    notes: ["Dogfood mode is a credibility proof. It does not run arbitrary code.", "The changed file content is deterministic for a given Base pack."]
  };
}
